### ISSUE TITLE
Sign subcommand does not respect RSIGN_CONFIG_DIR

### ISSUE THREAD

**Issue by nixberg** [jedisct1/rsign2#2]
Is there a particular reason the sign subcommand does not use [`sk_path_or_default`](https://github.com/jedisct1/rsign2/blob/149c93751694c96fd9db76dcfa24f702995a5a63/src/bin/rsign/main.rs#L196)?

In related news, I wrote [a snap](https://github.com/nixberg/rsign2) for rsign.

**Comment by jedisct1** [comment]
The function `sk_path_or_default()` creates a directory, or a directory hierarchy.
The `sign` command shouldn't create directories :)

But yes, it looks like ony the `generate` command currently handles `RSIGN_CONFIG_DIR`, and that should be fixed.

Thanks for reporting this.
