### ISSUE TITLE
Enhancement request: improve scriptablility

### ISSUE THREAD

**Issue by udf2457** [jedisct1/rsign2#4]
Woul be nice if `rsign` were given args to enable it to be more scriptable.  At the moment it expects key password to be typed in, a scriptable alternative for this (e.g. path to env file) would be very much appreciated.

**Comment by jedisct1** [comment]
You can use the `<` shell operator in order to get input data from a file instead of a keyboard.

`rsign2 ... < password.txt`

Works with anything that expects input from the keyboard :)

**Comment by Firaenix** [comment]
using < in macos doesnt work for me when passing a password.txt in, I still get prompted for the password.

Is there anyway around this?

**Comment by jedisct1** [comment]
@Firaenix You can use the original version: https://jedisct1.github.io/minisign/ 

`<` works as it should, and there's also a `-W` command-line flag to not use a password at all.

**Comment by jedisct1** [comment]
I released a new version of `rsign2`, that includes the same feature.

**Comment by passcod** [comment]
`rsign2` uses `rpassword`, which [reads /dev/tty](https://docs.rs/rpassword/latest/src/rpassword/lib.rs.html#116-122) instead of /dev/stdin, hence why `< file` doesn't work.

Though a bit clunky, I've successfully used good ol [`expect`](https://linux.die.net/man/1/expect) instead. If it helps anyone else:

```bash
expect <<EXP
spawn rsign generate -f -p minisign.pub -s minisign.key
expect "Password:"
send -- "$SIGNING_KEY_SECRET\r"
expect "Password (one more time):"
send -- "$SIGNING_KEY_SECRET\r"
expect eof
EXP
```

```bash
expect <<EXP
spawn rsign sign -s minisign.key -x "$file.sig" -t "$comment" "$file"
expect "Password:"
send -- "$SIGNING_KEY_SECRET\r"
expect eof
EXP
```

**Comment by jedisct1** [comment]
`rsign generate --passwordless` creates a key pair that doesn't require a password.

**Comment by passcod** [comment]
Yes, but in that case I _do_ want a password, just not interactively.
