### ISSUE TITLE
Consider migrating to `anyhow` for error handling

### ISSUE THREAD

**Issue by tiziano88** [jedisct1/rsign2#7]
https://docs.rs/anyhow/1.0.31/anyhow/

**Comment by tiziano88** [comment]
Happy to look into this myself if there is interest in merging.

**Comment by jedisct1** [comment]
Hi!

We don't have a lot of errors, and they are very simple.

So I rather not introduce a breaking change and an additional dependency with no real benefits.

**Comment by tiziano88** [comment]
No problem, understandable. The downside of piling up on the `minisign::*` types for errors is that they don't necessarily make sense at application level. For instance, [in my own PR](https://github.com/jedisct1/rsign2/pull/6), I had to create a `PError` and try to match its format instead of a more convenient type (e.g. `anyhow::Result`) that is more idiomatic for logging and preserves context. Anyway, your call of course, perhaps worth reconsidering later on.

Keep up the good work!

**Comment by tiziano88** [comment]
Just in case it was not clear: I was suggesting this only for the binary crate of course, not for the library.

**Comment by jedisct1** [comment]
Good point!

This will be useful if the binary gets a little bit bigger and more complex, but right now, it's just a small wrapper around the library that is unlikely to change much.

So, maybe we can wait for the next error handling crate :)
